server:
  port: 9010
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS}%clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'
spring:
  datasource:
    url: jdbc:mysql:///baizhanshopping?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
# \u914D\u7F6EMybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      table-prefix: bz_
      id-type: auto
  configuration:
    #???????????????????????????  ?true???????????????????????
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??sql??
dubbo:
  application:
    name: etao_order_service
  registry:
    address: zookeeper://43.136.14.183
    port: 2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.huangkai.etao_order_service.service

