server:
  port: 9009
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS}%clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'
spring:
  redis:
    host: 192.168.31.66
    port: 6379
    timeout: 30000
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1
        max-idle: 8
  # rabbitmq
  rabbitmq:
    host: 192.168.31.66
    port: 5672
    username: guest
    password: guest
    virtual-host: /

dubbo:
  application:
    name: etao_cart_service
  registry:
    address: zookeeper://43.136.14.183
    port: 2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.huangkai.etao_cart_service.service
